---
- name: "Create directory for {{ test_scenario.name }}"
  file:
    path: "{{ work_dir + '/tests/' + test_scenario.testcase + '/' + test_scenario.name }}"
    state: directory

- name: "Synchronize files for {{ test_scenario.name }}"
  ansible.builtin.synchronize:
    src: "{{ template_dir +'/kuttl/' + test_scenario.testcase + '/' }}"
    dest: "{{ work_dir + '/tests/' + test_scenario.testcase + '/' + test_scenario.name }}"

- name: "Find test templates for {{ test_scenario.name }}"
  find:
    paths: "{{ work_dir + '/tests/' + test_scenario.testcase + '/' + test_scenario.name }}"
    patterns: "*.j2"
    file_type: file
    hidden: true
    use_regex: false
    recurse: true
  register: test_templates

- name: "Process templates for {{ test_scenario.name }}"
  template:
    src: "{{ item.path }}"
    dest: "{{ item.path | regex_replace('.j2$', '') }}"
    mode: "preserve"
  loop: "{{ test_templates.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: "Delete template sources for {{ test_scenario.name }}"
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ test_templates.files }}"
  loop_control:
    label: "{{ item.path }}"
